[workspace]
resolver = "2"
members = ["metafile", "naming_convention", "progest"]

[workspace.dependencies]
metafile = { path = "metafile" }
naming_convention = { path = "naming_convention" }
progest = { path = "progest" }

